version: '3.8'
services:
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/innotech_backend-1.0.war:/usr/local/tomcat/webapps/help-service.war
    restart: on-failure